/*
 * Invoices
 * Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The payment mode or method through which the invoicer can accept the payments.
 */
@JsonAdapter(PaymentMethod.Adapter.class)public enum PaymentMethod {
  
  BANK_TRANSFER("BANK_TRANSFER"),
  
  CASH("CASH"),
  
  CHECK("CHECK"),
  
  CREDIT_CARD("CREDIT_CARD"),
  
  DEBIT_CARD("DEBIT_CARD"),
  
  PAYPAL("PAYPAL"),
  
  WIRE_TRANSFER("WIRE_TRANSFER"),
  
  OTHER("OTHER");

  private String value;

  PaymentMethod(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PaymentMethod fromValue(String value) {
    for (PaymentMethod b : PaymentMethod.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PaymentMethod> {
    @Override
    public void write(final JsonWriter jsonWriter, final PaymentMethod enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PaymentMethod read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PaymentMethod.fromValue(value);
    }
  }
}

