/*
 * Invoices
 * Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PhoneType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * The phone details. Includes the phone number and type.
 */
@ApiModel(description = "The phone details. Includes the phone number and type.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PhoneDetail {
  public static final String SERIALIZED_NAME_COUNTRY_CODE = "country_code";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  private String countryCode;

  public static final String SERIALIZED_NAME_NATIONAL_NUMBER = "national_number";
  @SerializedName(SERIALIZED_NAME_NATIONAL_NUMBER)
  private String nationalNumber;

  public static final String SERIALIZED_NAME_EXTENSION_NUMBER = "extension_number";
  @SerializedName(SERIALIZED_NAME_EXTENSION_NUMBER)
  private String extensionNumber;

  public static final String SERIALIZED_NAME_PHONE_TYPE = "phone_type";
  @SerializedName(SERIALIZED_NAME_PHONE_TYPE)
  private PhoneType phoneType;

  public PhoneDetail() {
  }

  public PhoneDetail countryCode(String countryCode) {
    
    
    if (countryCode != null && countryCode.length() < 1) {
      throw new IllegalArgumentException("Invalid value for countryCode. Length must be greater than or equal to 1.");
    }
    
    this.countryCode = countryCode;
    return this;
  }

   /**
   * The country calling code (CC), in its canonical international [E.164 numbering plan format](https://www.itu.int/rec/T-REC-E.164/en). The combined length of the CC and the national number must not be greater than 15 digits. The national number consists of a national destination code (NDC) and subscriber number (SN).
   * @return countryCode
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The country calling code (CC), in its canonical international [E.164 numbering plan format](https://www.itu.int/rec/T-REC-E.164/en). The combined length of the CC and the national number must not be greater than 15 digits. The national number consists of a national destination code (NDC) and subscriber number (SN).")

  public String getCountryCode() {
    return countryCode;
  }


  public void setCountryCode(String countryCode) {
    
    
    if (countryCode != null && countryCode.length() < 1) {
      throw new IllegalArgumentException("Invalid value for countryCode. Length must be greater than or equal to 1.");
    }
    this.countryCode = countryCode;
  }


  public PhoneDetail nationalNumber(String nationalNumber) {
    
    
    if (nationalNumber != null && nationalNumber.length() < 1) {
      throw new IllegalArgumentException("Invalid value for nationalNumber. Length must be greater than or equal to 1.");
    }
    
    this.nationalNumber = nationalNumber;
    return this;
  }

   /**
   * The national number, in its canonical international [E.164 numbering plan format](https://www.itu.int/rec/T-REC-E.164/en). The combined length of the country calling code (CC) and the national number must not be greater than 15 digits. The national number consists of a national destination code (NDC) and subscriber number (SN).
   * @return nationalNumber
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The national number, in its canonical international [E.164 numbering plan format](https://www.itu.int/rec/T-REC-E.164/en). The combined length of the country calling code (CC) and the national number must not be greater than 15 digits. The national number consists of a national destination code (NDC) and subscriber number (SN).")

  public String getNationalNumber() {
    return nationalNumber;
  }


  public void setNationalNumber(String nationalNumber) {
    
    
    if (nationalNumber != null && nationalNumber.length() < 1) {
      throw new IllegalArgumentException("Invalid value for nationalNumber. Length must be greater than or equal to 1.");
    }
    this.nationalNumber = nationalNumber;
  }


  public PhoneDetail extensionNumber(String extensionNumber) {
    
    
    if (extensionNumber != null && extensionNumber.length() < 1) {
      throw new IllegalArgumentException("Invalid value for extensionNumber. Length must be greater than or equal to 1.");
    }
    
    this.extensionNumber = extensionNumber;
    return this;
  }

   /**
   * The extension number.
   * @return extensionNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The extension number.")

  public String getExtensionNumber() {
    return extensionNumber;
  }


  public void setExtensionNumber(String extensionNumber) {
    
    
    if (extensionNumber != null && extensionNumber.length() < 1) {
      throw new IllegalArgumentException("Invalid value for extensionNumber. Length must be greater than or equal to 1.");
    }
    this.extensionNumber = extensionNumber;
  }


  public PhoneDetail phoneType(PhoneType phoneType) {
    
    
    
    
    this.phoneType = phoneType;
    return this;
  }

   /**
   * Get phoneType
   * @return phoneType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public PhoneType getPhoneType() {
    return phoneType;
  }


  public void setPhoneType(PhoneType phoneType) {
    
    
    
    this.phoneType = phoneType;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PhoneDetail instance itself
   */
  public PhoneDetail putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhoneDetail phoneDetail = (PhoneDetail) o;
    return Objects.equals(this.countryCode, phoneDetail.countryCode) &&
        Objects.equals(this.nationalNumber, phoneDetail.nationalNumber) &&
        Objects.equals(this.extensionNumber, phoneDetail.extensionNumber) &&
        Objects.equals(this.phoneType, phoneDetail.phoneType)&&
        Objects.equals(this.additionalProperties, phoneDetail.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryCode, nationalNumber, extensionNumber, phoneType, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhoneDetail {\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    nationalNumber: ").append(toIndentedString(nationalNumber)).append("\n");
    sb.append("    extensionNumber: ").append(toIndentedString(extensionNumber)).append("\n");
    sb.append("    phoneType: ").append(toIndentedString(phoneType)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("country_code");
    openapiFields.add("national_number");
    openapiFields.add("extension_number");
    openapiFields.add("phone_type");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("country_code");
    openapiRequiredFields.add("national_number");
    openapiRequiredFields.add("phone_type");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PhoneDetail
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PhoneDetail.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PhoneDetail is not found in the empty JSON string", PhoneDetail.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PhoneDetail.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("country_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `country_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country_code").toString()));
      }
      if (!jsonObj.get("national_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `national_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("national_number").toString()));
      }
      if ((jsonObj.get("extension_number") != null && !jsonObj.get("extension_number").isJsonNull()) && !jsonObj.get("extension_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `extension_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("extension_number").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PhoneDetail.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PhoneDetail' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PhoneDetail> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PhoneDetail.class));

       return (TypeAdapter<T>) new TypeAdapter<PhoneDetail>() {
           @Override
           public void write(JsonWriter out, PhoneDetail value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PhoneDetail read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PhoneDetail instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PhoneDetail given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PhoneDetail
  * @throws IOException if the JSON string is invalid with respect to PhoneDetail
  */
  public static PhoneDetail fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PhoneDetail.class);
  }

 /**
  * Convert an instance of PhoneDetail to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

