/*
 * Invoices
 * Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * The configuration for a QR code.
 */
@ApiModel(description = "The configuration for a QR code.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class QrConfig {
  public static final String SERIALIZED_NAME_WIDTH = "width";
  @SerializedName(SERIALIZED_NAME_WIDTH)
  private Integer width = 500;

  public static final String SERIALIZED_NAME_HEIGHT = "height";
  @SerializedName(SERIALIZED_NAME_HEIGHT)
  private Integer height = 500;

  public static final String SERIALIZED_NAME_ACTION = "action";
  @SerializedName(SERIALIZED_NAME_ACTION)
  private String action = "pay";

  public QrConfig() {
  }

  public QrConfig width(Integer width) {
    if (width != null && width < 150) {
      throw new IllegalArgumentException("Invalid value for width. Must be greater than or equal to 150.");
    }
    if (width != null && width > 500) {
      throw new IllegalArgumentException("Invalid value for width. Must be less than or equal to 500.");
    }
    
    
    this.width = width;
    return this;
  }

   /**
   * The width, in pixels, of the QR code image. Value is from &#x60;150&#x60; to &#x60;500&#x60;.
   * minimum: 150
   * maximum: 500
   * @return width
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "500", value = "The width, in pixels, of the QR code image. Value is from `150` to `500`.")

  public Integer getWidth() {
    return width;
  }


  public void setWidth(Integer width) {
    if (width != null && width < 150) {
      throw new IllegalArgumentException("Invalid value for width. Must be greater than or equal to 150.");
    }
    if (width != null && width > 500) {
      throw new IllegalArgumentException("Invalid value for width. Must be less than or equal to 500.");
    }
    
    this.width = width;
  }


  public QrConfig height(Integer height) {
    if (height != null && height < 150) {
      throw new IllegalArgumentException("Invalid value for height. Must be greater than or equal to 150.");
    }
    if (height != null && height > 500) {
      throw new IllegalArgumentException("Invalid value for height. Must be less than or equal to 500.");
    }
    
    
    this.height = height;
    return this;
  }

   /**
   * The height, in pixels, of the QR code image. Value is from &#x60;150&#x60; to &#x60;500&#x60;.
   * minimum: 150
   * maximum: 500
   * @return height
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "500", value = "The height, in pixels, of the QR code image. Value is from `150` to `500`.")

  public Integer getHeight() {
    return height;
  }


  public void setHeight(Integer height) {
    if (height != null && height < 150) {
      throw new IllegalArgumentException("Invalid value for height. Must be greater than or equal to 150.");
    }
    if (height != null && height > 500) {
      throw new IllegalArgumentException("Invalid value for height. Must be less than or equal to 500.");
    }
    
    this.height = height;
  }


  public QrConfig action(String action) {
    
    
    
    
    this.action = action;
    return this;
  }

   /**
   * The type of URL for which to generate a QR code. Valid values are &#x60;pay&#x60; and &#x60;details&#x60;.
   * @return action
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "pay", value = "The type of URL for which to generate a QR code. Valid values are `pay` and `details`.")

  public String getAction() {
    return action;
  }


  public void setAction(String action) {
    
    
    
    this.action = action;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the QrConfig instance itself
   */
  public QrConfig putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QrConfig qrConfig = (QrConfig) o;
    return Objects.equals(this.width, qrConfig.width) &&
        Objects.equals(this.height, qrConfig.height) &&
        Objects.equals(this.action, qrConfig.action)&&
        Objects.equals(this.additionalProperties, qrConfig.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(width, height, action, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QrConfig {\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("width");
    openapiFields.add("height");
    openapiFields.add("action");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to QrConfig
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!QrConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in QrConfig is not found in the empty JSON string", QrConfig.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("action") != null && !jsonObj.get("action").isJsonNull()) && !jsonObj.get("action").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `action` to be a primitive type in the JSON string but got `%s`", jsonObj.get("action").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!QrConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'QrConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<QrConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(QrConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<QrConfig>() {
           @Override
           public void write(JsonWriter out, QrConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public QrConfig read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             QrConfig instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of QrConfig given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of QrConfig
  * @throws IOException if the JSON string is invalid with respect to QrConfig
  */
  public static QrConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, QrConfig.class);
  }

 /**
  * Convert an instance of QrConfig to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

