/*
 * Invoices
 * Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TemplateItemSetting;
import com.konfigthis.client.model.TemplateSubtotalSetting;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * The template settings. Sets a template as the default template or edit template.
 */
@ApiModel(description = "The template settings. Sets a template as the default template or edit template.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class TemplateSettings {
  public static final String SERIALIZED_NAME_TEMPLATE_ITEM_SETTINGS = "template_item_settings";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_ITEM_SETTINGS)
  private List<TemplateItemSetting> templateItemSettings = null;

  public static final String SERIALIZED_NAME_TEMPLATE_SUBTOTAL_SETTINGS = "template_subtotal_settings";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_SUBTOTAL_SETTINGS)
  private List<TemplateSubtotalSetting> templateSubtotalSettings = null;

  public TemplateSettings() {
  }

  public TemplateSettings templateItemSettings(List<TemplateItemSetting> templateItemSettings) {
    
    
    
    
    this.templateItemSettings = templateItemSettings;
    return this;
  }

  public TemplateSettings addTemplateItemSettingsItem(TemplateItemSetting templateItemSettingsItem) {
    if (this.templateItemSettings == null) {
      this.templateItemSettings = new ArrayList<>();
    }
    this.templateItemSettings.add(templateItemSettingsItem);
    return this;
  }

   /**
   * The template item headers display preference.
   * @return templateItemSettings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The template item headers display preference.")

  public List<TemplateItemSetting> getTemplateItemSettings() {
    return templateItemSettings;
  }


  public void setTemplateItemSettings(List<TemplateItemSetting> templateItemSettings) {
    
    
    
    this.templateItemSettings = templateItemSettings;
  }


  public TemplateSettings templateSubtotalSettings(List<TemplateSubtotalSetting> templateSubtotalSettings) {
    
    
    
    
    this.templateSubtotalSettings = templateSubtotalSettings;
    return this;
  }

  public TemplateSettings addTemplateSubtotalSettingsItem(TemplateSubtotalSetting templateSubtotalSettingsItem) {
    if (this.templateSubtotalSettings == null) {
      this.templateSubtotalSettings = new ArrayList<>();
    }
    this.templateSubtotalSettings.add(templateSubtotalSettingsItem);
    return this;
  }

   /**
   * The template subtotal headers display preference.
   * @return templateSubtotalSettings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The template subtotal headers display preference.")

  public List<TemplateSubtotalSetting> getTemplateSubtotalSettings() {
    return templateSubtotalSettings;
  }


  public void setTemplateSubtotalSettings(List<TemplateSubtotalSetting> templateSubtotalSettings) {
    
    
    
    this.templateSubtotalSettings = templateSubtotalSettings;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TemplateSettings instance itself
   */
  public TemplateSettings putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateSettings templateSettings = (TemplateSettings) o;
    return Objects.equals(this.templateItemSettings, templateSettings.templateItemSettings) &&
        Objects.equals(this.templateSubtotalSettings, templateSettings.templateSubtotalSettings)&&
        Objects.equals(this.additionalProperties, templateSettings.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateItemSettings, templateSubtotalSettings, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateSettings {\n");
    sb.append("    templateItemSettings: ").append(toIndentedString(templateItemSettings)).append("\n");
    sb.append("    templateSubtotalSettings: ").append(toIndentedString(templateSubtotalSettings)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("template_item_settings");
    openapiFields.add("template_subtotal_settings");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TemplateSettings
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TemplateSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TemplateSettings is not found in the empty JSON string", TemplateSettings.openapiRequiredFields.toString()));
        }
      }
      if (jsonObj.get("template_item_settings") != null && !jsonObj.get("template_item_settings").isJsonNull()) {
        JsonArray jsonArraytemplateItemSettings = jsonObj.getAsJsonArray("template_item_settings");
        if (jsonArraytemplateItemSettings != null) {
          // ensure the json data is an array
          if (!jsonObj.get("template_item_settings").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `template_item_settings` to be an array in the JSON string but got `%s`", jsonObj.get("template_item_settings").toString()));
          }

          // validate the optional field `template_item_settings` (array)
          for (int i = 0; i < jsonArraytemplateItemSettings.size(); i++) {
            TemplateItemSetting.validateJsonObject(jsonArraytemplateItemSettings.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("template_subtotal_settings") != null && !jsonObj.get("template_subtotal_settings").isJsonNull()) {
        JsonArray jsonArraytemplateSubtotalSettings = jsonObj.getAsJsonArray("template_subtotal_settings");
        if (jsonArraytemplateSubtotalSettings != null) {
          // ensure the json data is an array
          if (!jsonObj.get("template_subtotal_settings").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `template_subtotal_settings` to be an array in the JSON string but got `%s`", jsonObj.get("template_subtotal_settings").toString()));
          }

          // validate the optional field `template_subtotal_settings` (array)
          for (int i = 0; i < jsonArraytemplateSubtotalSettings.size(); i++) {
            TemplateSubtotalSetting.validateJsonObject(jsonArraytemplateSubtotalSettings.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TemplateSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TemplateSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TemplateSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TemplateSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<TemplateSettings>() {
           @Override
           public void write(JsonWriter out, TemplateSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TemplateSettings read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TemplateSettings instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TemplateSettings given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TemplateSettings
  * @throws IOException if the JSON string is invalid with respect to TemplateSettings
  */
  public static TemplateSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TemplateSettings.class);
  }

 /**
  * Convert an instance of TemplateSettings to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

