openapi: 3.0.3
info:
  contact: {}
  description: "Use the Invoicing API to create, send, and manage invoices. You can\
    \ also use the API or webhooks to track invoice payments. When you send an invoice\
    \ to a customer, the invoice moves from draft to payable state. PayPal then emails\
    \ the customer a link to the invoice on the PayPal website. Customers with a PayPal\
    \ account can log in and pay the invoice with PayPal. Alternatively, customers\
    \ can pay as a guest with a debit card or credit card. For more information, see\
    \ the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\"\
    >Invoicing Integration Guide</a>."
  title: Invoices
  version: "2.3"
  x-konfig-has-globally-required-security: true
servers:
- description: PayPal Sandbox Environment
  url: https://api-m.sandbox.paypal.com
- description: PayPal Live Environment
  url: https://api-m.paypal.com
tags:
- description: "Use the `/invoices` resource to create, update, and send invoices\
    \ and invoice reminders. To manage invoices, you can also list invoices, show\
    \ details for invoices, delete draft invoices, and cancel sent invoices. You can\
    \ also record payments for invoices to mark them as fully or partially paid, or\
    \ record refunds for invoices to mark them as fully or partially refunded. You\
    \ can create QR codes for invoices that can be scanned, viewed, and paid by a\
    \ mobile phone."
  name: invoices
- description: "Use the `/templates` resource to create, list, show details for, update,\
    \ and delete invoice templates. Use the `/templates` resource when you create\
    \ a third-party invoicing application. For instance, a business can create a template\
    \ with predefined invoice data. Later, the business can select the template to\
    \ populate the invoice data.<blockquote><strong>Note:</strong> To upload a logo\
    \ to display on an invoice, you can use the <strong>Template Settings</strong>\
    \ dashboard to <a href=\"https://www.paypal.com/invoice/settings/templates\">create\
    \ a template</a>. When you create an invoice, you can use the URI for that logo.</blockquote>"
  name: templates
- description: Use the `/search-invoices` resource to search for and list invoices
    that match search criteria.
  name: search-invoices
- description: "Use the `/merchant-config` resource to create, update and show details\
    \ of merchant configuration."
  name: merchant-config
paths:
  /v2/invoicing/invoices:
    get:
      description: "Lists invoices. To filter the invoices that appear in the response,\
        \ you can specify one or more optional query parameters."
      operationId: Invoices_getInvoices
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/read
      summary: List invoices
      tags:
      - invoices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-invoicing-invoices
      x-accepts: application/json
    post:
      description: "Creates a draft invoice. To move the invoice from a draft to payable\
        \ state, you must <a href=\"#invoices_send\">send the invoice</a>.<br/><br/>In\
        \ the JSON request body, include invoice details including merchant information.\
        \ The <code>invoice</code> object must include an <code>items</code> array.<blockquote><strong>Note:</strong>\
        \ The merchant that you specify in an invoice must have a PayPal account in\
        \ good standing.</blockquote>."
      operationId: Invoices_createDraftInvoice
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/readwrite
      summary: Create draft invoice
      tags:
      - invoices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-invoicing-invoices
      x-content-type: application/json
      x-accepts: application/json
  /v2/invoicing/invoices/{invoice_id}/send:
    post:
      description: "Sends or schedules an invoice, by ID, to be sent to a customer.\
        \ The action depends on the invoice issue date:<ul><li>If the invoice issue\
        \ date is current or in the past, sends the invoice immediately.</li><li>If\
        \ the invoice issue date is in the future, schedules the invoice to be sent\
        \ on that date.</li></ul>To suppress the merchant's email notification, set\
        \ the `send_to_invoicer` body parameter to `false`. To send the invoice through\
        \ a share link and not through PayPal, set the <code>send_to_recipient</code>\
        \ parameter to <code>false</code> in the <code>notification</code> object.\
        \ The <code>send_to_recipient</code> parameter does not apply to a future\
        \ issue date because the invoice is scheduled to be sent through PayPal on\
        \ that date.<blockquote><strong>Notes:</strong><ul><li>After you send an invoice,\
        \ resending it has no effect.</li><li>To send a notification for updates,\
        \ <a href=\"#invoices_update\">update the invoice</a> and set the <code>send_to_recipient</code>\
        \ body parameter to <code>true</code>.</li></ul></blockquote>"
      operationId: Invoices_sendInvoice
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/readwrite
      summary: Send invoice
      tags:
      - invoices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-invoicing-invoices-invoice_id-send
      x-content-type: application/json
      x-accepts: application/json
  /v2/invoicing/invoices/{invoice_id}/remind:
    post:
      description: "Sends a reminder to the payer about an invoice, by ID. In the\
        \ JSON request body, include a `notification` object that defines the subject\
        \ of the reminder and other details."
      operationId: Invoices_sendReminder
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/readwrite
      summary: Send invoice reminder
      tags:
      - invoices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-invoicing-invoices-invoice_id-remind
      x-content-type: application/json
      x-accepts: application/json
  /v2/invoicing/invoices/{invoice_id}/cancel:
    post:
      description: "Cancels a sent invoice, by ID, and, optionally, sends a notification\
        \ about the cancellation to the payer, merchant, and CC: emails."
      operationId: Invoices_cancelSentInvoice
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/readwrite
      summary: Cancel sent invoice
      tags:
      - invoices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-invoicing-invoices-invoice_id-cancel
      x-content-type: application/json
      x-accepts: application/json
  /v2/invoicing/invoices/{invoice_id}/payments:
    post:
      description: "Records a payment for the invoice. If no payment is due, the invoice\
        \ is marked as `PAID`. Otherwise, the invoice is marked as `PARTIALLY PAID`."
      operationId: Invoices_recordPayment
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/readwrite
      summary: Record payment for invoice
      tags:
      - invoices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-invoicing-invoices-invoice_id-payments
      x-content-type: application/json
      x-accepts: application/json
  /v2/invoicing/invoices/{invoice_id}/payments/{transaction_id}:
    delete:
      description: "Deletes an external payment, by invoice ID and transaction ID."
      operationId: Invoices_deleteExternalPayment
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/readwrite
      summary: Delete external payment
      tags:
      - invoices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--v2-invoicing-invoices-invoice_id-payments-transaction_id
      x-accepts: application/json
  /v2/invoicing/invoices/{invoice_id}/refunds:
    post:
      description: "Records a refund for the invoice. If all payments are refunded,\
        \ the invoice is marked as `REFUNDED`. Otherwise, the invoice is marked as\
        \ `PARTIALLY REFUNDED`."
      operationId: Invoices_recordRefund
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/readwrite
      summary: Record refund for invoice
      tags:
      - invoices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-invoicing-invoices-invoice_id-refunds
      x-content-type: application/json
      x-accepts: application/json
  /v2/invoicing/invoices/{invoice_id}/refunds/{transaction_id}:
    delete:
      description: "Deletes an external refund, by invoice ID and transaction ID."
      operationId: Invoices_deleteExternalRefund
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/readwrite
      summary: Delete external refund
      tags:
      - invoices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--v2-invoicing-invoices-invoice_id-refunds-transaction_id
      x-accepts: application/json
  /v2/invoicing/invoices/{invoice_id}/generate-qr-code:
    post:
      description: "Generates a QR code for an invoice, by ID. The QR code is a PNG\
        \ image in <a href=\"https://www.base64encode.org/\">Base64-encoded</a> format\
        \ that corresponds to the invoice ID. You can generate a QR code for an invoice\
        \ and add it to a paper or PDF invoice. When customers use their mobile devices\
        \ to scan the QR code, they are redirected to the PayPal mobile payment flow\
        \ where they can view the invoice and pay online with PayPal or a credit card.\
        \ Before you get a QR code, you must <a href=\"#invoices_create\">create an\
        \ invoice</a> and <a href=\"#invoices_send\">send an invoice</a> to move the\
        \ invoice from a draft to payable state. Do not include an email address if\
        \ you do not want the invoice emailed."
      operationId: Invoices_generateQrCode
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/readwrite
      summary: Generate QR code
      tags:
      - invoices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-invoicing-invoices-invoice_id-generate-qr-code
      x-content-type: application/json
      x-accepts: application/json
  /v2/invoicing/generate-next-invoice-number:
    post:
      description: "Generates the next invoice number that is available to the merchant.\
        \ The next invoice number uses the prefix and suffix from the last invoice\
        \ number and increments the number by one. For example, the next invoice number\
        \ after `INVOICE-1234` is `INVOICE-1235`."
      operationId: Invoices_generateNextInvoiceNumber
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/readwrite
      summary: Generate invoice number
      tags:
      - invoices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-invoicing-generate-next-invoice-number
      x-accepts: application/json
  /v2/invoicing/invoices/{invoice_id}:
    delete:
      description: "Deletes a draft or scheduled invoice, by ID. Deletes invoices\
        \ in the draft or scheduled state only. For invoices that have already been\
        \ sent, you can <a href=\"/docs/api/invoicing/v2/#invoices_cancel\">cancel\
        \ the invoice</a>. After you delete a draft or scheduled invoice, you can\
        \ no longer use it or show its details. However, you can reuse its invoice\
        \ number."
      operationId: Invoices_deleteDraftOrScheduledInvoice
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/readwrite
      summary: Delete invoice
      tags:
      - invoices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--v2-invoicing-invoices-invoice_id
      x-accepts: application/json
    get:
      description: "Shows details for an invoice, by ID."
      operationId: Invoices_getDetails
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/read
      summary: Show invoice details
      tags:
      - invoices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-invoicing-invoices-invoice_id
      x-accepts: application/json
    put:
      description: "Fully updates an invoice, by ID. In the JSON request body, include\
        \ a complete `invoice` object. This call does not support partial updates."
      operationId: Invoices_updateFullInvoice
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/readwrite
      summary: Fully update invoice
      tags:
      - invoices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--v2-invoicing-invoices-invoice_id
      x-content-type: application/json
      x-accepts: application/json
  /v2/invoicing/search-invoices:
    post:
      description: "Searches for and lists invoices that match search criteria. If\
        \ you pass multiple criteria, the response lists invoices that match all criteria."
      operationId: Searchinvoices_list
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/read
      summary: Search for invoices
      tags:
      - search-invoices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-invoicing-search-invoices
      x-content-type: application/json
      x-accepts: application/json
  /v2/invoicing/templates:
    get:
      description: "Lists merchant-created templates with associated details. The\
        \ associated details include the emails, addresses, and phone numbers from\
        \ the user's PayPal profile.<br/>The user can select which values to show\
        \ in the business information section of their template."
      operationId: Templates_listDetails
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/read
      summary: List templates
      tags:
      - templates
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-invoicing-templates
      x-accepts: application/json
    post:
      description: "Creates an invoice template. You can use details from this template\
        \ to create an invoice. You can create up to 50 templates.<blockquote><strong>Note:</strong>\
        \ Every merchant starts with three PayPal system templates that are optimized\
        \ for the unit type billed. The template includes `Quantity`, `Hours`, and\
        \ `Amount`.</blockquote>"
      operationId: Templates_createTemplate
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/readwrite
      summary: Create template
      tags:
      - templates
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-invoicing-templates
      x-content-type: application/json
      x-accepts: application/json
  /v2/invoicing/templates/{template_id}:
    delete:
      description: "Deletes a template, by ID."
      operationId: Templates_deleteById
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/readwrite
      summary: Delete template
      tags:
      - templates
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--v2-invoicing-templates-template_id
      x-accepts: application/json
    get:
      description: "Shows details for a template, by ID."
      operationId: Templates_showDetailsById
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/read
      summary: Show template details
      tags:
      - templates
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-invoicing-templates-template_id
      x-accepts: application/json
    put:
      description: "Fully updates a template, by ID. In the JSON request body, include\
        \ a complete `template` object. This call does not support partial updates."
      operationId: Templates_updateFullTemplate
      security:
      - Oauth2:
        - https://uri.paypal.com/services/invoicing/invoices/readwrite
      summary: Fully update template
      tags:
      - templates
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--v2-invoicing-templates-template_id
      x-content-type: application/json
      x-accepts: application/json
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 authentication
      flows:
        clientCredentials:
          scopes:
            https://uri.paypal.com/services/invoicing/invoices/read: For Reading the
              invoice details.
            https://uri.paypal.com/services/invoicing/invoices/readwrite: "For managing\
              \ (Create, Update, Delete) invoice."
            https://uri.paypal.com/services/invoicing/internal: Manage invoice resource
              internal clients.
          tokenUrl: /v1/oauth2/token
      type: oauth2
      x-konfig-globally-required-security: true

